services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  frontend:
    build:
      context: frontend
      args:
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
    ports:
      - "3000:80"
    tty: true
  backend:
    build:
      context: backend
    environment:
      POSTGRES_CONNECTION_STRING: ${POSTGRES_CONNECTION_STRING}
      FRONTEND_URL: ${FRONTEND_URL}
      PORT: 4000
    ports:
      - "4000:4000"
volumes:
  dbdata:
